# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/constrs_1/new/esp.xdc

# Block Designs: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/zynqWithWifiExp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqWithWifiExp || ORIG_REF_NAME==zynqWithWifiExp} -quiet] -quiet

# IP: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_processing_system7_0_0/zynqWithWifiExp_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqWithWifiExp_processing_system7_0_0 || ORIG_REF_NAME==zynqWithWifiExp_processing_system7_0_0} -quiet] -quiet

# IP: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_myipBCM_0_0/zynqWithWifiExp_myipBCM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqWithWifiExp_myipBCM_0_0 || ORIG_REF_NAME==zynqWithWifiExp_myipBCM_0_0} -quiet] -quiet

# IP: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_ps7_0_axi_periph_1/zynqWithWifiExp_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqWithWifiExp_ps7_0_axi_periph_1 || ORIG_REF_NAME==zynqWithWifiExp_ps7_0_axi_periph_1} -quiet] -quiet

# IP: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_rst_ps7_0_100M_1/zynqWithWifiExp_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqWithWifiExp_rst_ps7_0_100M_1 || ORIG_REF_NAME==zynqWithWifiExp_rst_ps7_0_100M_1} -quiet] -quiet

# IP: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_auto_pc_0/zynqWithWifiExp_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqWithWifiExp_auto_pc_0 || ORIG_REF_NAME==zynqWithWifiExp_auto_pc_0} -quiet] -quiet

# XDC: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_processing_system7_0_0/zynqWithWifiExp_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynqWithWifiExp_processing_system7_0_0 || ORIG_REF_NAME==zynqWithWifiExp_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_rst_ps7_0_100M_1/zynqWithWifiExp_rst_ps7_0_100M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynqWithWifiExp_rst_ps7_0_100M_1 || ORIG_REF_NAME==zynqWithWifiExp_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_rst_ps7_0_100M_1/zynqWithWifiExp_rst_ps7_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynqWithWifiExp_rst_ps7_0_100M_1 || ORIG_REF_NAME==zynqWithWifiExp_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_rst_ps7_0_100M_1/zynqWithWifiExp_rst_ps7_0_100M_1_ooc.xdc

# XDC: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/ip/zynqWithWifiExp_auto_pc_0/zynqWithWifiExp_auto_pc_0_ooc.xdc

# XDC: /home/nazmul/research/zedWithWifiExp/zedWithWifiExp.srcs/sources_1/bd/zynqWithWifiExp/zynqWithWifiExp_ooc.xdc
